/* Datos iniciales de respaldo para la variante que usa localStorage. */
/* Cada producto contiene identidad, categoria, unidad, precio, stock, texto e imagen. */
window.INITIAL_INVENTORY = [
  {
    id: 'lentejas',
    name: 'Lentejas',
    category: 'Legumbres',
    unit: 'libra',
    price: 1.2,
    stock: 25,
    icon: '🫘',
    description: 'Seleccionadas para sopas y guisos.',
    image: 'basic_baseData/img/lentejas.svg',
  },
  {
    id: 'frejol',
    name: 'Frejol rojo',
    category: 'Legumbres',
    unit: 'libra',
    price: 1.35,
    stock: 18,
    icon: '🫘',
    description: 'Textura suave y sabor de casa.',
    image: 'basic_baseData/img/lentejas.svg',
  },
  {
    id: 'tomate',
    name: 'Tomate rinon',
    category: 'Verduras',
    unit: 'libra',
    price: 0.8,
    stock: 30,
    icon: '🍅',
    description: 'Rojo, firme y listo para tu ensalada.',
    image: 'basic_baseData/img/tomates.svg',
  },
  {
    id: 'naranja',
    name: 'Naranja',
    category: 'Frutas',
    unit: 'libra',
    price: 0.55,
    stock: 40,
    icon: '🍊',
    description: 'Dulce, jugosa y recien cosechada.',
    image: 'basic_baseData/img/naranjas.svg',
  },
  {
    id: 'arroz',
    name: 'Arroz',
    category: 'Granos',
    unit: 'libra',
    price: 0.65,
    stock: 50,
    icon: '🍚',
    description: 'El basico que nunca puede faltar.',
    image: '',
  },
  {
    id: 'platano',
    name: 'Platano verde',
    category: 'Frutas',
    unit: 'unidad',
    price: 0.25,
    stock: 35,
    icon: '🍌',
    description: 'Ideal para patacones y sopas.',
    image: 'basic_baseData/img/naranjas.svg',
  },
]
